### PR TITLE
copy_splice(): don't leak pipe fds if splice() fails

### PR DESCRIPTION
**Pull request by wjt**
Previously, if either splice() call failed, the function would return
without closing pin or pout.  (One way it might fail is if the process
reading from the file system closes its fd without consuming the whole
file.)

To fix this, wrap the pair of fds in a new struct PipeFds with an
idempotent close() function, () and a Drop impl that calls it.  This
allows copy_splice() to propagate errors encountered while closing
either pipe fd after an otherwise-successful copy, while guaranteeing
that close() will be called on both pipe fds.

If close() fails on both pipe fds, return the error from the 'in' side,
which matches the old behaviour.

This addresses the fd-leak part of #18.

### CODE REVIEW

**Comment by wjt** [comment]
It might be nice to add a test. It's easy to see the leak manually: run `lsof -p $PID`, run `dd if=/some/file bs=1 count=1` for a file larger than one byte, run `lsof -p $PID` again and observe a pair of pipes.

The test I have in mind is to determine what the maximum number of FDs is, then call open(path); close(path) that many times + 1, and see if it works. But … what I don't quite understand is how the process got to ~100,000 then ran out, given `/proc/$PID/limits` shows the "Max open files" limit as 1024 and the hard limit as 1,048,576 (an order of magnitude more).

**Review by gaul — APPROVED** [review]

**Comment by kahing** [comment]
wow it's been a long time since I looked at this code. This mostly looks good, one comment:

for the most part my approach for libc wrapping has been:
1. wrap at a level as close to libc as possible, while using rust primitives if possible (ex: Path, Result)
2. provide high level abstraction if it's useful (ex: rlibc::File)

at one point I was hoping to pull out the stuff for 1 to a separate crate (so 2 can be more opinionated)

In this case I'd leave `rlibc::pipe` as is, as add a `rlibc::Pipe` that uses `rlibc::pipe`. Understand that it's been a few years so you probably won't pick this up, so I will try to do that in the next couple days.

**Comment by wjt** [comment]
I'm afraid I indeed won't have time to pick this back up.

**Comment by gaul** [comment]
See #51 for an alternate approach.

**Comment by gaul** [comment]
Superseded by #51.

**Pull request closed without merging**
